version: '2.1'
services:
    redis:
        image: 'redis:5.0.5'
        # command: redis-server --requirepass redispass

    postgres:
        build:
            context: ./postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
            - POSTGRES_DB=airflow
        # Uncomment these lines to persist data on the local filesystem.
            - PGDATA= data/postgres
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        
        restart: always

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        restart: unless-stopped

    webserver:
        build:
            context: ./airflow
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=Celery
            # - AIRFLOW__WEBSERVER__RBAC=true
            - AIRFLOW__WEBSERVER__WORKERS=2
            - AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL=1800
            - AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT=300
            - ADMIN_USER=${ADMIN_USER:-danpra}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
            - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./airflow/plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        build:
            context: ./airflow
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build:
            context: ./airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./airflow/plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=Celery
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
            - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        build:
            context: ./airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./airflow/plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=Celery
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
            - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: worker