version: '2.1'
services:
    redis:
        image: 'bitnami/redis:6.0.6'
        command: redis-server --requirepass ${REDIS_PASSWORD:-changeme}
        restart: always
        environment:
            #- ALLOW_EMPTY_PASSWORD=yes
            - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}
        volumes:
            - ./services/redis/redis-persistence:/bitnami/redis/data

    redisinsight:
      image: redislabs/redisinsight
      ports:
          - 8001:8001
      depends_on:
          - redis


    postgres:
        build:
            context: ./services/postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
            - POSTGRES_DB=airflow
        # Uncomment these lines to persist data on the local filesystem.
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - pgdata:/var/lib/postgresql/data

        
        restart: always

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        restart: unless-stopped

    webserver:
        build:
            context: ./services/airflow
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=Celery
            - AIRFLOW__WEBSERVER__RBAC=true
            - AIRFLOW__WEBSERVER__WORKERS=2
            - AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL=1800
            - AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT=300
            - ADMIN_USER=${ADMIN_USER:-danpra}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}
        volumes:
            - ./services/airflow/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./airflow/plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    scheduler:
        build:
            context: ./services/airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./services/airflow/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./airflow/plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=Celery
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}
        command: scheduler

    worker:
        build:
            context: ./services/airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./services/airflow/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./airflow/plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=Celery
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}
        command: worker


volumes:
    pgdata:
        external: true
